export const monthsMock = [
  {
    id: "cl80ra8j70g2e0ckesnso0lr5",
    name: "Jan",
    mesNumber: 1,
    institutions: [
      {
        id: "cl84j5u0k021y0blu31p6spor",
        name: "teste",
        amount: "0",
        expirationDate: "2022-10-10",
        shoppings: [],
      },
    ],
  },
  {
    id: "cl80rbdxp0g3q0ckehzkhuspl",
    name: "Fev",
    mesNumber: 2,
    institutions: [],
  },
  {
    id: "cl80rjxwr0eby0blsb3pqp6ec",
    name: "Mar",
    mesNumber: 3,
    institutions: [],
  },
  {
    id: "cl81txspd02bw0dlw96ltlkwk",
    name: "Abr",
    mesNumber: 4,
    institutions: [],
  },
  {
    id: "cl81ty5di02dk0dlwdns3cgdm",
    name: "Mai",
    mesNumber: 5,
    institutions: [],
  },
  {
    id: "cl81tytkf03l90bk94ym77ovz",
    name: "Jun",
    mesNumber: 6,
    institutions: [],
  },
  {
    id: "cl81tz7jt02gi0dlw80nq92cw",
    name: "Jul",
    mesNumber: 7,
    institutions: [],
  },
  {
    id: "cl81tzixh03oj0bk911i8z6sa",
    name: "Ago",
    mesNumber: 8,
    institutions: [],
  },
  {
    id: "cl81u025f02jw0dlwi7g1fqwx",
    name: "Set",
    mesNumber: 9,
    institutions: [
      {
        id: "cl83ezpao2b3l0bk9buajxyrc",
        name: "Debito",
        amount: null,
        expirationDate: "2022-10-10",
        shoppings: [
          {
            id: "cl84v1hfb0kak0bkf4w3wu6ui",
            description: "agua",
            amount: "100,00",
            responsible: "matheus",
          },
          {
            id: "cl84v1rdy0jzz0bluyhste7uj",
            description: "oi",
            amount: "50,00",
            responsible: "matheus",
          },
          {
            id: "cl84v2f7v0kcr0bkf60rm6j3a",
            description: "devolver para cc urgencia",
            amount: "200,00",
            responsible: "matheus",
          },
          {
            id: "cl84v2qr70k2a0blux9v2ew7q",
            description: "deveolver para cc urgencia",
            amount: "100,00",
            responsible: "matheus",
          },
          {
            id: "cl84v31nu0k390bluum20xr5a",
            description: "deveolver para cc urgencia",
            amount: "100,00",
            responsible: "matheus",
          },
          {
            id: "cl84v3ewg0k480bluc8zuebt8",
            description: "devolver para cc urgencia",
            amount: "200,00",
            responsible: "matheus",
          },
          {
            id: "cl84v3ph70k4r0bluggrsxsqs",
            description: "energia",
            amount: "100,00",
            responsible: "pai",
          },
          {
            id: "cl84v40qw0kg80bkf5nzotoeq",
            description: "gas",
            amount: "130,00",
            responsible: "pai",
          },
          {
            id: "cl84v4dsy0kgu0bkfv6ntyrhf",
            description: "intenert",
            amount: "110,00",
            responsible: "mae",
          },
          {
            id: "cl84v4owj0k6f0blumawdau1d",
            description: "emprestimo mae",
            amount: "100,00",
            responsible: "mae",
          },
        ],
      },
      {
        id: "cl83f04rj29wj0dlw9248k5ms",
        name: "Nunbank",
        amount: null,
        expirationDate: "2022-10-07",
        shoppings: [],
      },
      {
        id: "cl83f0i3e29xa0dlwuliv9e04",
        name: "Inter",
        amount: null,
        expirationDate: "2022-10-07",
        shoppings: [],
      },
      {
        id: "cl83f0vc02b610bk9q2b38oud",
        name: "Santander",
        amount: null,
        expirationDate: "2022-10-10",
        shoppings: [],
      },
      {
        id: "cl83f13s92b7c0bk90z6i8r9e",
        name: "Bradesco",
        amount: null,
        expirationDate: "2022-10-06",
        shoppings: [],
      },
    ],
  },
  {
    id: "cl81u112s03ue0bk9eoqi524h",
    name: "Out",
    mesNumber: 10,
    institutions: [
      {
        id: "cl83f1koh2b9h0bk9o9ft3rg9",
        name: "Debito",
        amount: null,
        expirationDate: "2022-10-10",
        shoppings: [],
      },
    ],
  },
  {
    id: "cl81u19mv02oh0dlwj49e5gy3",
    name: "Nov",
    mesNumber: 11,
    institutions: [],
  },
  {
    id: "cl81u1oht03xf0bk9rud55ie1",
    name: "Dez",
    mesNumber: 12,
    institutions: [],
  },
];
